### ISSUE TITLE
Scrapy하는 도중 문제 발생

### ISSUE THREAD

**Issue by sktkddn777** [KPUCE2021SP/LiC#16]
키위즐 사이트를 scrapy하는 과정에서 너무 많은 호출로 인해서인지 사이트에서 접근을 막아버렸음. 키위즐 사이트에 대기업 위주로 스택들이 있어서 crawling을 시도한건데 막혀버려서 직접 기업 홈페이지에서 스택을 가져와야 할 것 같다

**Comment by KKodiac** [comment]
Workin' on it 😭

**Comment by bjo6300** [comment]
shit

**Comment by KKodiac** [comment]
#18 pr로 인해 해결 되었습니다. 이슈 닫을게여
