### ISSUE TITLE
ECS문제 

### ISSUE THREAD

**Issue by sktkddn777** [KPUCE2021SP/LiC#22]
ECS는 AWS에서 1년 무료 사용을 지원해주지 않는거 같아 
돈이 빠져나간다...

**Comment by KKodiac** [comment]
[AWS Free tier pricing](https://aws.amazon.com/free/?p=gsrc&c=ho_ddc&all-free-tier.sort-by=item.additionalFields.SortRank&all-free-tier.sort-order=asc&awsf.Free%20Tier%20Types=*all&awsf.Free%20Tier%20Categories=*all&all-free-tier.q=ECS&all-free-tier.q_operator=AND) 여기서는 2200시간/한달 6개월간 무료라고 나와있는데?

근데 찝찝하면 다른 서비스 찾아보니까 일단
 - [Heroku](https://devcenter.heroku.com/articles/container-registry-and-runtime)(도커 이미지만 허브에 올려서 히로쿠에 이미지로 배포) 
 - GCP(GCB, $300 credit제공, 따로 문서는 제대로 안봄)

**Comment by sktkddn777** [comment]
아 그래?? 내가 설정을 잘못했나보네 그럼 일단은 ECS로 가보자
