### ISSUE TITLE
Converging Collections in MongoDB?

### ISSUE THREAD

**Issue by KKodiac** [KPUCE2021SP/LiC#25]
Scrapy에서 MongoDB collection을 하나로 합치는게 좋을거 같은데 어떻게 생각혀? 

이렇게 하면 실제 데이터를 호출 시에 여러 컬렉션에서 호출을 할 필요가 없으니 실제 클라이언트 부분에서 속도 개선이 있을거 같은데
지금 생각나는 고려 사항에는, 

- 각 스파이더 파이프라인에서 하나의 컬렉션으로 UPDATE 또는 INSERT 작업 시에 일어나는 오버헤드
- 몽고디비에서 하나의 컬렉션에 IO가 동시에 일어날 때 어떻게 처리가 되는지? 
- 비동기로 처리가 가능한지? 

정도인데, 하나의 컬렉션으로 합치면 또 일어날 수 있는 문제가 어떤게 있을까?

현재는 각 도커 컨테이너가 동시에 실행되면서 각각 스파이더에 지정된 컬렉션에 데이터가 저장이 돼.

**Comment by sktkddn777** [comment]
고려 사항은 이 3가지 말고는 지금은 생각 안나는데
클라이언트 부분에서 속도 개선이 있을까???
3가지 컬렉션에 동시에 요청을 보낼 수도 있지 않아??(이건 아직 잘 몰라서 하는말)

**Comment by KKodiac** [comment]
요청이 많을 때를 생각해보면 있을거 같은데 
생각해보니 async로 콜백을 작성하면 될거 같다. ㅇㅋㅇㅋ 
피드백 감사합니당
