### ISSUE TITLE
firebase authentication에 관해서

### ISSUE THREAD

**Issue by sktkddn777** [KPUCE2021SP/LiC#32]
github에 로그인할 때 로그인 이메일과 유저 이름이 다른 경우가 있다.
이런 경우에는 로그인 할 때 유저이름으로 로그인 해달라고 미리 UI 에서 부탁을 하면 될 거 같은데
다른 의견 있나요?

**Comment by KKodiac** [comment]
UI에서 유저에게 명시하는 부분도 분명히 좋은 생각 이라고 생각합니다.
근데 제 의견은 우리 프로젝트 형식 상 우리가 공부하며 진행하는 부분이 크다고 생각하기 때문에 
이와 같은 예외처리를 해보는 것도 좋다고 생각합니다!

**Comment by KKodiac** [comment]
@bjo6300  어떻게 생각하시나요?

**Comment by bjo6300** [comment]
firebase에서 받아올 수 있는게 이메일, photoUrl, uid, displayname인데 이거로 유저이름 알 수 있는지 찾아보고
안되면 예외처리해서 edittext로 받아오는 것이 좋을 것 같아요 KKodiac님!

**Comment by KKodiac** [comment]
화긴

**Comment by bjo6300** [comment]
여태까지 해봤는데 난 실패함
다를경우에만 예외처리해서 유저네임 받는게 정신건강에 이롭긴해
아니면 멘토님 찬스?
