### ISSUE TITLE
scrapy mongodb mapping

### ISSUE THREAD

**Issue by sktkddn777** [KPUCE2021SP/LiC#6]
각 사이트에서 받아온 데이터에 대한 mapping을 어떻게 해야 되지요...???

**Comment by sktkddn777** [comment]
1. 번역기를 사용해서 기업 이름을 다 한글로 만든다
2. 기업이름으로  매핑을 한다

더 좋은 방법 생각해보자

**Comment by KKodiac** [comment]
각 사이트에서 보여지는 json 형식을 맞춰야 될거 같은데, 그걸 일단 각 호스트 사이트마다 보여줄 수 있어?

그리고 일단 1차적으로 scrapy에서 제공하는 기능 중에 참고할 것들이,
우리 response를 각 스파이더마다 양식?을 통합할 수 있도록 다룰 커스텀 [middleware](https://docs.scrapy.org/en/latest/topics/spider-middleware.html)을 만들거나,
[Item Loader](https://docs.scrapy.org/en/latest/topics/loaders.html) 을 사용해서  통합된 item 객체 형식을 만들고, 거기에 중복된 기업 이름 키 값만 없애면 될듯한데... 자세한건 더 찾아볼게

**Comment by KKodiac** [comment]
Item 구조 다시 짜서 매핑할 필요 없어졌으니까 이슈 닫을게요
