### ISSUE TITLE
게시판 댓글 사용자 프로필 사진

### ISSUE THREAD

**Issue by KKodiac** [KPUCE2021SP/LiC#78]
**Describe the bug**
-  게시판 댓글 사용자의 프로필 사진이 제대로 안나옴.
realtime db에 comment 디렉토리에 반영되는 프로필 이미지 url 자체도 댓글 쓴 사용자의 url이 아닌 
추측이지만 댓글이 종속된 board 글을 작성한 사용자의 프로필 url 이 들어가는 거 같음. 

- board 글을 작성한 사용자 또한 프로필 사진이 current-user, 즉 현재 앱에 로그인한 사용자의 프로필 사진으로 보임

**To Reproduce**
1. 게시판 글 작성
2. 해당 글의 댓글 작성
3. Firebase RTDB 확인 
4. comment/{comment-datetime+user-profile}/userphoto 답글을 쓴 사용자가 아닌 것을 확인
  4.1. 예를들어 내가 쓴 댓글의 userphoto 값이 준일이 프로필 url 값으로 되어있음
5. 앱 내에서 board / comment 프로필 사진이 현재 viewer 의 프로필 사진으로 전체 적용된 것 확인

**Expected behavior**
각 사용자의 알맞게 프로필 사진 적용

**Screenshots**
![bug1](https://user-images.githubusercontent.com/35219323/133832733-3cbf98d7-4a90-4ecb-8a01-acf4698c4c64.PNG)

![bug2](https://user-images.githubusercontent.com/35219323/133832858-8a14443e-4276-40d3-9b0b-30075cb2491c.PNG)

**Smartphone (please complete the following information):**
 - OS: [e.g. iOS]: Android
 - 에뮬: Pixel 3 XL API30
 - Version [e.g. 22]: minSDK 21 / targetSDK 30

**Comment by bjo6300** [comment]
얼른 고쳐볼게요 홍팀장님!

**Comment by KKodiac** [comment]
;;;;👍

**Comment by bjo6300** [comment]
고쳤으니 닫을게요 captain Hong님
